import { test, expect, type Page } from '@playwright/test'
async function openHistory(page: Page) {
  const expand = page.getByRole('button', { name: '검색 기록 펼치기' })
  if (await expand.isVisible()) await expand.click()
}
async function sample(page: Page) {
  await openHistory(page)
  await page.getByRole('button', { name: '디자인 예시 둘러보기' }).click()
  await page.getByRole('button', { name: '벡터 검색이란? 가상 데이터' }).click()
}
test('same canvas, suggestion only fills, samples, selection, relation, history restore and delete', async ({ page }) => {
  let calls = 0
  page.on('request', request => { if (request.url().includes('/api/search')) calls++ })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '호기심이 이어지는 곳' })).toBeVisible()
  await page.getByRole('button', { name: '벡터 검색이란?', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '검색 질문' })).toHaveValue('벡터 검색이란?')
  expect(calls).toBe(0)
  await page.locator('.react-flow').evaluate(el => el.setAttribute('data-original-canvas', 'yes'))
  await sample(page)
  await expect(page.locator('.page-card')).toHaveCount(6)
  await expect(page.locator('.react-flow')).toHaveAttribute('data-original-canvas', 'yes')
  await expect(page.locator('.sample-badge')).toHaveText('디자인 예시 · 가상 데이터')
  await page.getByRole('button', { name: '답변 펼치기' }).click()
  await page.getByRole('button', { name: '출처 1 선택' }).click()
  await expect(page.getByRole('region', { name: '출처 상세' })).toBeVisible()
  await page.getByRole('button', { name: '상세 닫기' }).click()
  await page.getByRole('button', { name: '답변 접기' }).click()
  await page.locator('.edge-label').first().click({ force: true })
  await expect(page.getByRole('region', { name: '관계 상세' })).toBeVisible()
  await page.getByRole('button', { name: '상세 닫기' }).click()
  await page.reload()
  await openHistory(page)
  await page.getByRole('button', { name: '벡터 검색이란? 예시', exact: true }).click()
  await expect(page.locator('.page-card')).toHaveCount(6)
  expect(calls).toBe(0)
  await openHistory(page)
  await page.getByRole('button', { name: '벡터 검색이란? 기록 삭제' }).click()
  await expect(page.locator('.page-card')).toHaveCount(0)
  await expect(page.getByText('검색 기록이 여기에 쌓입니다.')).toBeVisible()
})
test('IME Enter does not submit, failed API never silently loads a sample', async ({ page }) => {
  let calls = 0
  await page.route('**/api/search', async route => { calls++; await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: '검색 API 키를 설정하세요.' }) }) })
  await page.goto('/')
  const input = page.getByRole('textbox', { name: '검색 질문' })
  await input.fill('벡터 검색')
  await input.dispatchEvent('compositionstart')
  await input.press('Enter')
  expect(calls).toBe(0)
  await input.dispatchEvent('compositionend')
  await page.getByRole('button', { name: '검색 실행' }).click()
  await expect(page.getByRole('alert')).toContainText('검색 API 키를 설정하세요.')
  await expect(page.locator('.page-card')).toHaveCount(0)
  await expect(page.locator('.sample-badge')).toHaveCount(0)
})
test('flight conditions collected before search and no horizontal document overflow', async ({ page }) => {
  await page.route('**/api/search', async route => {
    const body = route.request().postDataJSON()
    const ev = (type: string, data: object, seq: number) => `data: ${JSON.stringify({ version: 1, request_id: body.request_id, job_id: 'j', seq, type, data })}\n\n`
    await route.fulfill({ contentType: 'text/event-stream', body: ev('clarification', { kind: 'flight' }, 1) + ev('done', { status: 'completed', failed_parts: [] }, 2) })
  })
  await page.goto('/')
  await page.getByRole('button', { name: '오사카 최저가 항공권', exact: true }).click()
  await page.getByRole('button', { name: '검색 실행' }).click()
  await expect(page.getByRole('form', { name: '항공권 검색 조건' })).toBeVisible()
  await expect(page.getByLabel('출발 공항')).toHaveValue('')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
